version: '3.8'

services:
  lbweb-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4321:4321"
    volumes:
      # Mount source code for hot reload
      - ./src:/app/src
      - ./public:/app/public
      - ./lbw-data:/app/lbw-data
      - ./astro.config.mjs:/app/astro.config.mjs
      - ./tsconfig.json:/app/tsconfig.json
      # Exclude node_modules to avoid conflicts
      - /app/node_modules
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
